version: '3'

services:
  email_rpc:
    container_name: email_rpc
    build: python/
    restart: always
    
    networks:
      - microservice
      - default

networks:
  default:
    external:
      name: email_network
  microservice:
    external:
      name: microservice_network